nomesCidades = [
    'Marília - Brasil', 
    'Tupã - Brasil',
    'Buenos Aires - Argentina',
    'Washington DC - Estados Unidos',
    'Carácas - Venezuela',
    'São Paulo - Brasil',
    'Rio de Janeiro - Brasil',
    'Nova York - Estados Unidos',
    'Paris - França',
    'Londres - Inglaterra',
    'Tóquio - Japão',
    'Pequim - China',
    'Roma - Itália',
    'Berlim - Alemanha',
    'Madri - Espanha',
    'Moscou - Rússia',
    'Toronto - Itália',
    'Sydney - Austrália',
    'Cidade do Cabo - África do Sul',
    'Dubai - Emirados Árabes Unidos',
    'Los Angeles - Estados Unidos',
    'Chicago - Estados Unidos',
    'Cidade do México - México',
    'Lisboa - Portugal',
    'Barcelona - Espanha',
    'Atenas - Grécia',
    'Seul - Coreia do Sul',
    'Bangkok - Tailândia',
    'Istambul - Turquia',
    'Cairo - Egito',
    'Delhi - Índia',
    'Hong Kong - China',
    'Porto - Portugal',
    'Amsterdã - Países Baixos',
    'Viena - Itália',
    'Praga - República Tcheca',
    'Zurique - Suíça',
    'Dublin - Irlanda',
    'Montevidéu - Uruguai',
    'Santiago - Chile'
]

nomesPatos = [
    "Quackthor", "Lord Plumage", "Sir Puddlebeak", "Dr. Quacktavius", "Ducanator", "Feathergeist", "Barão do Brejo", "Capitão Penafria", "Almirante Quackwell", "Professor Patozônio", "Ducky McSteam", "Patoquântico", "O Ornitron", "Vaporwing", "Count Duckvlad", "Major Plumaflame", "Archibald Quacksworth", "Mestre Plumaluz", "Duckborg XIX", "Plumachron", "Pato Supremo de Andromeda", "Quackarion", "Visconde Penasombra", "Sir Nebulapato", "Patozord Alfa", "Comandante Penáltron", "Lord Quacktus", "Dr. Pluma Cósmica", "General Puddlecore", "Pato Ômega"
]

